version: '1'

services:
  server:
    container_name: cors-proksy
    image: amakilla/cors-proksy:latest
    command: sh -c "npm install && node server.js"
    ports:
      - "80:80"
      - "8080:8080"
    restart: always
